# Generated by Django 6.0.5 on 2026-05-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='upload_date',
        ),
    ]
